// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GreenTeaProgrammers/WhereChildBus/backend/domain/repository/ent/child"
	"github.com/GreenTeaProgrammers/WhereChildBus/backend/domain/repository/ent/childphoto"
	"github.com/GreenTeaProgrammers/WhereChildBus/backend/domain/repository/ent/predicate"
	"github.com/google/uuid"
)

// ChildPhotoQuery is the builder for querying ChildPhoto entities.
type ChildPhotoQuery struct {
	config
	ctx        *QueryContext
	order      []childphoto.OrderOption
	inters     []Interceptor
	predicates []predicate.ChildPhoto
	withChild  *ChildQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChildPhotoQuery builder.
func (cpq *ChildPhotoQuery) Where(ps ...predicate.ChildPhoto) *ChildPhotoQuery {
	cpq.predicates = append(cpq.predicates, ps...)
	return cpq
}

// Limit the number of records to be returned by this query.
func (cpq *ChildPhotoQuery) Limit(limit int) *ChildPhotoQuery {
	cpq.ctx.Limit = &limit
	return cpq
}

// Offset to start from.
func (cpq *ChildPhotoQuery) Offset(offset int) *ChildPhotoQuery {
	cpq.ctx.Offset = &offset
	return cpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cpq *ChildPhotoQuery) Unique(unique bool) *ChildPhotoQuery {
	cpq.ctx.Unique = &unique
	return cpq
}

// Order specifies how the records should be ordered.
func (cpq *ChildPhotoQuery) Order(o ...childphoto.OrderOption) *ChildPhotoQuery {
	cpq.order = append(cpq.order, o...)
	return cpq
}

// QueryChild chains the current query on the "child" edge.
func (cpq *ChildPhotoQuery) QueryChild() *ChildQuery {
	query := (&ChildClient{config: cpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(childphoto.Table, childphoto.FieldID, selector),
			sqlgraph.To(child.Table, child.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, childphoto.ChildTable, childphoto.ChildColumn),
		)
		fromU = sqlgraph.SetNeighbors(cpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ChildPhoto entity from the query.
// Returns a *NotFoundError when no ChildPhoto was found.
func (cpq *ChildPhotoQuery) First(ctx context.Context) (*ChildPhoto, error) {
	nodes, err := cpq.Limit(1).All(setContextOp(ctx, cpq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{childphoto.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cpq *ChildPhotoQuery) FirstX(ctx context.Context) *ChildPhoto {
	node, err := cpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ChildPhoto ID from the query.
// Returns a *NotFoundError when no ChildPhoto ID was found.
func (cpq *ChildPhotoQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cpq.Limit(1).IDs(setContextOp(ctx, cpq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{childphoto.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cpq *ChildPhotoQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := cpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ChildPhoto entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ChildPhoto entity is found.
// Returns a *NotFoundError when no ChildPhoto entities are found.
func (cpq *ChildPhotoQuery) Only(ctx context.Context) (*ChildPhoto, error) {
	nodes, err := cpq.Limit(2).All(setContextOp(ctx, cpq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{childphoto.Label}
	default:
		return nil, &NotSingularError{childphoto.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cpq *ChildPhotoQuery) OnlyX(ctx context.Context) *ChildPhoto {
	node, err := cpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ChildPhoto ID in the query.
// Returns a *NotSingularError when more than one ChildPhoto ID is found.
// Returns a *NotFoundError when no entities are found.
func (cpq *ChildPhotoQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cpq.Limit(2).IDs(setContextOp(ctx, cpq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{childphoto.Label}
	default:
		err = &NotSingularError{childphoto.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cpq *ChildPhotoQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := cpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ChildPhotos.
func (cpq *ChildPhotoQuery) All(ctx context.Context) ([]*ChildPhoto, error) {
	ctx = setContextOp(ctx, cpq.ctx, "All")
	if err := cpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ChildPhoto, *ChildPhotoQuery]()
	return withInterceptors[[]*ChildPhoto](ctx, cpq, qr, cpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cpq *ChildPhotoQuery) AllX(ctx context.Context) []*ChildPhoto {
	nodes, err := cpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ChildPhoto IDs.
func (cpq *ChildPhotoQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if cpq.ctx.Unique == nil && cpq.path != nil {
		cpq.Unique(true)
	}
	ctx = setContextOp(ctx, cpq.ctx, "IDs")
	if err = cpq.Select(childphoto.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cpq *ChildPhotoQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := cpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cpq *ChildPhotoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cpq.ctx, "Count")
	if err := cpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cpq, querierCount[*ChildPhotoQuery](), cpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cpq *ChildPhotoQuery) CountX(ctx context.Context) int {
	count, err := cpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cpq *ChildPhotoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cpq.ctx, "Exist")
	switch _, err := cpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cpq *ChildPhotoQuery) ExistX(ctx context.Context) bool {
	exist, err := cpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChildPhotoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cpq *ChildPhotoQuery) Clone() *ChildPhotoQuery {
	if cpq == nil {
		return nil
	}
	return &ChildPhotoQuery{
		config:     cpq.config,
		ctx:        cpq.ctx.Clone(),
		order:      append([]childphoto.OrderOption{}, cpq.order...),
		inters:     append([]Interceptor{}, cpq.inters...),
		predicates: append([]predicate.ChildPhoto{}, cpq.predicates...),
		withChild:  cpq.withChild.Clone(),
		// clone intermediate query.
		sql:  cpq.sql.Clone(),
		path: cpq.path,
	}
}

// WithChild tells the query-builder to eager-load the nodes that are connected to
// the "child" edge. The optional arguments are used to configure the query builder of the edge.
func (cpq *ChildPhotoQuery) WithChild(opts ...func(*ChildQuery)) *ChildPhotoQuery {
	query := (&ChildClient{config: cpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cpq.withChild = query
	return cpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		IsDuplicate bool `json:"is_duplicate,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChildPhoto.Query().
//		GroupBy(childphoto.FieldIsDuplicate).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cpq *ChildPhotoQuery) GroupBy(field string, fields ...string) *ChildPhotoGroupBy {
	cpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChildPhotoGroupBy{build: cpq}
	grbuild.flds = &cpq.ctx.Fields
	grbuild.label = childphoto.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		IsDuplicate bool `json:"is_duplicate,omitempty"`
//	}
//
//	client.ChildPhoto.Query().
//		Select(childphoto.FieldIsDuplicate).
//		Scan(ctx, &v)
func (cpq *ChildPhotoQuery) Select(fields ...string) *ChildPhotoSelect {
	cpq.ctx.Fields = append(cpq.ctx.Fields, fields...)
	sbuild := &ChildPhotoSelect{ChildPhotoQuery: cpq}
	sbuild.label = childphoto.Label
	sbuild.flds, sbuild.scan = &cpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChildPhotoSelect configured with the given aggregations.
func (cpq *ChildPhotoQuery) Aggregate(fns ...AggregateFunc) *ChildPhotoSelect {
	return cpq.Select().Aggregate(fns...)
}

func (cpq *ChildPhotoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cpq); err != nil {
				return err
			}
		}
	}
	for _, f := range cpq.ctx.Fields {
		if !childphoto.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cpq.path != nil {
		prev, err := cpq.path(ctx)
		if err != nil {
			return err
		}
		cpq.sql = prev
	}
	return nil
}

func (cpq *ChildPhotoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ChildPhoto, error) {
	var (
		nodes       = []*ChildPhoto{}
		withFKs     = cpq.withFKs
		_spec       = cpq.querySpec()
		loadedTypes = [1]bool{
			cpq.withChild != nil,
		}
	)
	if cpq.withChild != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, childphoto.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ChildPhoto).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ChildPhoto{config: cpq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cpq.withChild; query != nil {
		if err := cpq.loadChild(ctx, query, nodes, nil,
			func(n *ChildPhoto, e *Child) { n.Edges.Child = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cpq *ChildPhotoQuery) loadChild(ctx context.Context, query *ChildQuery, nodes []*ChildPhoto, init func(*ChildPhoto), assign func(*ChildPhoto, *Child)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ChildPhoto)
	for i := range nodes {
		if nodes[i].child_photos == nil {
			continue
		}
		fk := *nodes[i].child_photos
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(child.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "child_photos" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (cpq *ChildPhotoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cpq.querySpec()
	_spec.Node.Columns = cpq.ctx.Fields
	if len(cpq.ctx.Fields) > 0 {
		_spec.Unique = cpq.ctx.Unique != nil && *cpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cpq.driver, _spec)
}

func (cpq *ChildPhotoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(childphoto.Table, childphoto.Columns, sqlgraph.NewFieldSpec(childphoto.FieldID, field.TypeUUID))
	_spec.From = cpq.sql
	if unique := cpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cpq.path != nil {
		_spec.Unique = true
	}
	if fields := cpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, childphoto.FieldID)
		for i := range fields {
			if fields[i] != childphoto.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cpq *ChildPhotoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cpq.driver.Dialect())
	t1 := builder.Table(childphoto.Table)
	columns := cpq.ctx.Fields
	if len(columns) == 0 {
		columns = childphoto.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cpq.sql != nil {
		selector = cpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cpq.ctx.Unique != nil && *cpq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cpq.predicates {
		p(selector)
	}
	for _, p := range cpq.order {
		p(selector)
	}
	if offset := cpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChildPhotoGroupBy is the group-by builder for ChildPhoto entities.
type ChildPhotoGroupBy struct {
	selector
	build *ChildPhotoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cpgb *ChildPhotoGroupBy) Aggregate(fns ...AggregateFunc) *ChildPhotoGroupBy {
	cpgb.fns = append(cpgb.fns, fns...)
	return cpgb
}

// Scan applies the selector query and scans the result into the given value.
func (cpgb *ChildPhotoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cpgb.build.ctx, "GroupBy")
	if err := cpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChildPhotoQuery, *ChildPhotoGroupBy](ctx, cpgb.build, cpgb, cpgb.build.inters, v)
}

func (cpgb *ChildPhotoGroupBy) sqlScan(ctx context.Context, root *ChildPhotoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cpgb.fns))
	for _, fn := range cpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cpgb.flds)+len(cpgb.fns))
		for _, f := range *cpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChildPhotoSelect is the builder for selecting fields of ChildPhoto entities.
type ChildPhotoSelect struct {
	*ChildPhotoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cps *ChildPhotoSelect) Aggregate(fns ...AggregateFunc) *ChildPhotoSelect {
	cps.fns = append(cps.fns, fns...)
	return cps
}

// Scan applies the selector query and scans the result into the given value.
func (cps *ChildPhotoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cps.ctx, "Select")
	if err := cps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChildPhotoQuery, *ChildPhotoSelect](ctx, cps.ChildPhotoQuery, cps, cps.inters, v)
}

func (cps *ChildPhotoSelect) sqlScan(ctx context.Context, root *ChildPhotoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cps.fns))
	for _, fn := range cps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
