steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/wherechildbus/gcr.io/wherechildbus/where_child_bus-grpc",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "gcr.io/wherechildbus/gcr.io/wherechildbus/where_child_bus-grpc"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      [
        "run",
        "deploy",
        "where-child-bus-grpc",
        "--image=gcr.io/wherechildbus/gcr.io/wherechildbus/where_child_bus-grpc",
        "--region=your-region",
        "--set-env-vars=DSN=$$DSN,DB_USER_NAME=$$DB_USER_NAME,DB_PASSWORD=$$DB_PASSWORD,DB_ADDR=$$DB_ADDR,DB_NAME=$$DB_NAME,PORT=$$PORT,ModeDev=$$ModeDev",
      ]
timeout: "1600s"
