FROM python:3.11.6-slim

WORKDIR /machine-learning
COPY ./requirements.lock /machine-learning/

RUN sed '/-e/d' requirements.lock > requirements.txt
RUN pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu

# 必要なライブラリをインストール
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0

COPY ./src /machine-learning/src

ENV PYTHONPATH "${PYTHONPATH}:/machine-learning/src/"

# TODO: server.pyをproto-genから切り出し
ENTRYPOINT ["python", "src/proto-gen/machine_learning/v1/server.py"]
