// Code generated by ent, DO NOT EDIT.

package childbusassociation

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/GreenTeaProgrammers/WhereChildBus/backend/domain/repository/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.FieldLTE(FieldID, id))
}

// ChildID applies equality check predicate on the "child_id" field. It's identical to ChildIDEQ.
func ChildID(v uuid.UUID) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.FieldEQ(FieldChildID, v))
}

// BusID applies equality check predicate on the "bus_id" field. It's identical to BusIDEQ.
func BusID(v uuid.UUID) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.FieldEQ(FieldBusID, v))
}

// ChildIDEQ applies the EQ predicate on the "child_id" field.
func ChildIDEQ(v uuid.UUID) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.FieldEQ(FieldChildID, v))
}

// ChildIDNEQ applies the NEQ predicate on the "child_id" field.
func ChildIDNEQ(v uuid.UUID) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.FieldNEQ(FieldChildID, v))
}

// ChildIDIn applies the In predicate on the "child_id" field.
func ChildIDIn(vs ...uuid.UUID) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.FieldIn(FieldChildID, vs...))
}

// ChildIDNotIn applies the NotIn predicate on the "child_id" field.
func ChildIDNotIn(vs ...uuid.UUID) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.FieldNotIn(FieldChildID, vs...))
}

// BusIDEQ applies the EQ predicate on the "bus_id" field.
func BusIDEQ(v uuid.UUID) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.FieldEQ(FieldBusID, v))
}

// BusIDNEQ applies the NEQ predicate on the "bus_id" field.
func BusIDNEQ(v uuid.UUID) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.FieldNEQ(FieldBusID, v))
}

// BusIDIn applies the In predicate on the "bus_id" field.
func BusIDIn(vs ...uuid.UUID) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.FieldIn(FieldBusID, vs...))
}

// BusIDNotIn applies the NotIn predicate on the "bus_id" field.
func BusIDNotIn(vs ...uuid.UUID) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.FieldNotIn(FieldBusID, vs...))
}

// BusTypeEQ applies the EQ predicate on the "bus_type" field.
func BusTypeEQ(v BusType) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.FieldEQ(FieldBusType, v))
}

// BusTypeNEQ applies the NEQ predicate on the "bus_type" field.
func BusTypeNEQ(v BusType) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.FieldNEQ(FieldBusType, v))
}

// BusTypeIn applies the In predicate on the "bus_type" field.
func BusTypeIn(vs ...BusType) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.FieldIn(FieldBusType, vs...))
}

// BusTypeNotIn applies the NotIn predicate on the "bus_type" field.
func BusTypeNotIn(vs ...BusType) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.FieldNotIn(FieldBusType, vs...))
}

// HasChild applies the HasEdge predicate on the "child" edge.
func HasChild() predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChildTable, ChildColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChildWith applies the HasEdge predicate on the "child" edge with a given conditions (other predicates).
func HasChildWith(preds ...predicate.Child) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(func(s *sql.Selector) {
		step := newChildStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBus applies the HasEdge predicate on the "bus" edge.
func HasBus() predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BusTable, BusColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBusWith applies the HasEdge predicate on the "bus" edge with a given conditions (other predicates).
func HasBusWith(preds ...predicate.Bus) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(func(s *sql.Selector) {
		step := newBusStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChildBusAssociation) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChildBusAssociation) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChildBusAssociation) predicate.ChildBusAssociation {
	return predicate.ChildBusAssociation(sql.NotPredicates(p))
}
