# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: where_child_bus/v1/station.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from where_child_bus.v1 import resources_pb2 as where__child__bus_dot_v1_dot_resources__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n where_child_bus/v1/station.proto\x12\x12where_child_bus.v1\x1a\"where_child_bus/v1/resources.proto\"q\n\x14UpdateStationRequest\x12\x1f\n\x0bguardian_id\x18\x01 \x01(\tR\nguardianId\x12\x1c\n\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n\x08latitude\x18\x03 \x01(\x01R\x08latitude\"N\n\x15UpdateStationResponse\x12\x35\n\x07station\x18\x01 \x01(\x0b\x32\x1b.where_child_bus.v1.StationR\x07station\"5\n\x1cGetStationListByBusIdRequest\x12\x15\n\x06\x62us_id\x18\x01 \x01(\tR\x05\x62usId\"\xd3\x01\n\x1dGetStationListByBusIdResponse\x12\x37\n\x08stations\x18\x01 \x03(\x0b\x32\x1b.where_child_bus.v1.StationR\x08stations\x12\x42\n\tguardians\x18\x02 \x03(\x0b\x32$.where_child_bus.v1.GuardianResponseR\tguardians\x12\x35\n\x08\x63hildren\x18\x03 \x03(\x0b\x32\x19.where_child_bus.v1.ChildR\x08\x63hildren2\xf4\x01\n\x0eStationService\x12\x64\n\rUpdateStation\x12(.where_child_bus.v1.UpdateStationRequest\x1a).where_child_bus.v1.UpdateStationResponse\x12|\n\x15GetStationListByBusId\x12\x30.where_child_bus.v1.GetStationListByBusIdRequest\x1a\x31.where_child_bus.v1.GetStationListByBusIdResponseB\xef\x01\n\x16\x63om.where_child_bus.v1B\x0cStationProtoP\x01Zfgithub.com/GreenTeaProgrammers/WhereChildBus/backend/proto-gen/go/where_child_bus/v1;where_child_busv1\xa2\x02\x03WXX\xaa\x02\x10WhereChildBus.V1\xca\x02\x10WhereChildBus\\V1\xe2\x02\x1cWhereChildBus\\V1\\GPBMetadata\xea\x02\x11WhereChildBus::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'where_child_bus.v1.station_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.where_child_bus.v1B\014StationProtoP\001Zfgithub.com/GreenTeaProgrammers/WhereChildBus/backend/proto-gen/go/where_child_bus/v1;where_child_busv1\242\002\003WXX\252\002\020WhereChildBus.V1\312\002\020WhereChildBus\\V1\342\002\034WhereChildBus\\V1\\GPBMetadata\352\002\021WhereChildBus::V1'
  _globals['_UPDATESTATIONREQUEST']._serialized_start=92
  _globals['_UPDATESTATIONREQUEST']._serialized_end=205
  _globals['_UPDATESTATIONRESPONSE']._serialized_start=207
  _globals['_UPDATESTATIONRESPONSE']._serialized_end=285
  _globals['_GETSTATIONLISTBYBUSIDREQUEST']._serialized_start=287
  _globals['_GETSTATIONLISTBYBUSIDREQUEST']._serialized_end=340
  _globals['_GETSTATIONLISTBYBUSIDRESPONSE']._serialized_start=343
  _globals['_GETSTATIONLISTBYBUSIDRESPONSE']._serialized_end=554
  _globals['_STATIONSERVICE']._serialized_start=557
  _globals['_STATIONSERVICE']._serialized_end=801
# @@protoc_insertion_point(module_scope)
