name: Deployment of machine learning system to CloudRun

on:
  push:
    branches:
      - develop
      - feature/machine-learning/cicd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build Docker image
        run: |
          docker build \
            --build-arg PROJECT_ID=${{ secrets.PROJECT_ID }} \
            --build-arg BUCKET_NAME=${{ secrets.BUCKET_NAME }} \
            --tag=gcr.io/${{ secrets.GCP_PROJECT_NAME_FOR_ML }}/${{ secrets.GCP_IMAGE_NAME_FOR_ML }}:latest \
            --file=./machine_learning/Dockerfile \
            --platform linux/amd64 ./machine_learning

      - name: Push Docker image to Artifact Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_NAME_FOR_ML }}/${{ secrets.GCP_IMAGE_NAME_FOR_ML }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.GCP_IMAGE_NAME_FOR_ML }} \
            --image gcr.io/${{ secrets.GCP_PROJECT_NAME_FOR_ML }}/${{ secrets.GCP_IMAGE_NAME_FOR_ML }}:latest \
            --region ${{ secrets.REGION }} \
            --platform managed
